.TH shut 1 2013-02-12 "shut"
.SH NAME
shut \- Tool to force logout of users after 30 minutes.
.SH SYNOPSIS
.B shut
.SH DESCRIPTION
shut is part of BUC Customizer, a tool to customize guest session of public
computers in the library of Fermo.
.SH COPYRIGHT
This manual page is Copyright 2013 Andrea Colangelo <warp10@ubuntu.com>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later
version published by the Free Software Foundation.
